services:
  user-db:
    image: postgres:17
    container_name: ms-user-db
    environment:
      POSTGRES_DB: ms-user-ms
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pass
    ports:
      - "5435:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  email-db:
    image: postgres:17
    container_name: ms-email-db
    environment:
      POSTGRES_DB: ms-email-ms
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pass
    ports:
      - "5433:5432"
    volumes:
      - email_pgdata:/var/lib/postgresql/data

volumes:
  user_pgdata:
  email_pgdata:
