services:
  postgres:
    image: postgres:17
    container_name: ms-email-db
    environment:
      POSTGRES_DB: ms-email-ms
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: