services:
  postgres:
    image: postgres:17
    container_name: ms-user-db
    environment:
      POSTGRES_DB: ms-user-ms
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pass
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: