spring:
  application:
    name: email-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ms-email-ms
    username: postgres-user
    password: postgres-pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}

  flyway:
    enabled: true
    location: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080


